# Generated by Django 2.2.4 on 2019-08-25 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190825_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat',
            new_name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='gallery/category/'),
            preserve_default=False,
        ),
    ]
