# Generated by Django 2.2.4 on 2019-08-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190825_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(default='', upload_to='gallery/category/'),
        ),
    ]
