# Generated by Django 2.2.4 on 2019-08-27 15:44

from django.db import migrations
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_image_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='icon',
            field=fontawesome.fields.IconField(blank=True, max_length=60),
        ),
    ]
